name: check
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  check:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
      - run: npm ci
      - run: npm run check
